"""Add extraction_reason to applications

Revision ID: 040e68045a6d
Revises: 65ea7d7e8b93
Create Date: 2026-09-14 14:08:22.422391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '040e68045a6d'
down_revision: Union[str, Sequence[str], None] = '65ea7d7e8b93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('extraction_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'extraction_reason')
    # ### end Alembic commands ###
