"""Add recommendation fields

Revision ID: 37cc1574b349
Revises: e8f2d8ac04fd
Create Date: 2026-09-12 02:21:14.520864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37cc1574b349'
down_revision: Union[str, Sequence[str], None] = 'e8f2d8ac04fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendations', sa.Column('source', sa.String(length=50), nullable=True))
    op.add_column('recommendations', sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'DISMISSED', name='recommendationstatus'), nullable=False))
    op.add_column('recommendations', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendations', 'is_active')
    op.drop_column('recommendations', 'status')
    op.drop_column('recommendations', 'source')
    # ### end Alembic commands ###
