"""Add extraction_note to applications

Revision ID: 65ea7d7e8b93
Revises: f38de65d290b
Create Date: 2026-09-14 13:05:58.907363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65ea7d7e8b93'
down_revision: Union[str, Sequence[str], None] = 'f38de65d290b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('extraction_note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'extraction_note')
    # ### end Alembic commands ###
