"""Add questions_extracted and images

Revision ID: f38de65d290b
Revises: 37cc1574b349
Create Date: 2026-09-14 02:08:59.324436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f38de65d290b'
down_revision: Union[str, Sequence[str], None] = '37cc1574b349'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('applications', sa.Column('questions_extracted', sa.Boolean(), nullable=False))
    op.add_column('questions', sa.Column('field_type', sa.String(length=50), nullable=True))
    op.add_column('questions', sa.Column('is_required', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'is_required')
    op.drop_column('questions', 'field_type')
    op.drop_column('applications', 'questions_extracted')
    op.drop_table('images')
    # ### end Alembic commands ###
